version: '3.9'

services:
  hydro:
    build: 
      context: ./
      dockerfile: base/python/Dockerfile
      args:
        service_dir: "bot"
    init: true
    tty: true
    container_name: hydro
    restart: unless-stopped
    volumes:
      - ./bot/bin:/app/bin
      - ./base/Python/lib:/app/lib
    environment:
      DATABASE: "postgresql://postgres"
      LOG_LEVEL: "info"
      REDIS: "redis://redis:6379"
    depends_on:
      - redis
      - postgres

  rpi:
    build: 
      context: ./
      dockerfile: base/python/Dockerfile
      args:
        service_dir: "farmer"
    init: true
    tty: true
    container_name: rpi
    restart: unless-stopped
    volumes:
      - ./farmer/bin:/app/bin
      - ./base/Python/lib:/app/lib
    environment:
      DATABASE: "postgresql://postgres"
      LOG_LEVEL: "info"
      REDIS: "redis://redis:6379"
    depends_on:
      - redis
      - postgres

  metrics:
    build: 
      context: ./
      dockerfile: base/python/Dockerfile
      args:
        service_dir: "metrics"
    init: true
    tty: true
    container_name: metrics
    restart: unless-stopped
    volumes:
      - ./metrics/bin:/app/bin
      - ./base/Python/lib:/app/lib
    environment:
      PORT: "8003"
      DATABASE: "postgresql://postgres"
      LOG_LEVEL: "info"
      REDIS: "redis://redis:6379"
    depends_on:
      - redis
      - postgres

  api:
    container_name: api
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5m
      timeout: 5s
      retries: 3
      start_period: 15s

  caddy:
    container_name: caddy
    restart: unless-stopped
    build:
      context: ./caddy
      dockerfile: ./Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/caddy_data:/data
      - ./data/caddy_config:/config
    depends_on:
      - api
    environment:
      PROXY_BACKEND: api
      PROXY_PORT: 8000

  frontend:
    container_name: frontend
    build:
      context: frontend
    ports:
      - 8001:8001
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    depends_on:
      - api

  nginx:
    container_name: nginx
    build: nginx/
    restart: always
    ports:
      - "8002:8002"
    deploy:
      mode: replicated
      replicas: 1

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    deploy:
      mode: replicated
      replicas: 1 
      
  prometheus-push-gateway:
    container_name: prometheus-push-gateway
    image: prom/pushgateway
    ports:
      - 9091:9091

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources

  postgres:
    container_name: postgres
    restart: always
    image: postgres:alpine
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: NxVhhyU9p3
      POSTGRES_DB: hydrodb
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=hydro@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=NxVhhyU9p3
      - POSTGRES_USER=postgres
      - POSTGRES_PW=NxVhhyU9p3
      - POSTGRES_DB=hydrodb
      - PGADMIN_MAIL=hydro@pgadmin.com
      - PGADMIN_PW=NxVhhyU9p3
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
    restart: always

volumes:
  prom_data:
  caddy_data:
  caddy_config:
