global:
  scrape_interval: 120s
  scrape_timeout: 60s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets: []
scrape_configs:
- job_name: pushed-metrics
  scrape_interval: 5s
  scrape_timeout: 4s
  honor_labels: true
  honor_timestamps: true
  static_configs:
    - targets:
      - "prometheus-push-gateway:9091"
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - prometheus:9090
- job_name: fastapi
  scrape_interval: 10s
  metrics_path: /metrics
  static_configs:
    - targets: 
      - api:8000
